import { ICongress } from "@/types/congress";

export const fakeCongresses: ICongress[] = [
  {
    id: 1,
    name: "International Conference on Artificial Intelligence",
    startDate: new Date("2025-05-12"),
    endDate: new Date("2025-05-15"),
    place: "São Paulo, Brasil",
    submissionDeadline: new Date("2025-03-20"),
    reviewsPerArticle: 3,
  },
  {
    id: 2,
    name: "Global Blockchain & Web3 Summit",
    startDate: new Date("2025-06-02"),
    endDate: new Date("2025-06-05"),
    place: "Lisboa, Portugal",
    submissionDeadline: new Date("2025-04-10"),
    reviewsPerArticle: 2,
  },
  {
    id: 3,
    name: "Climate Change & Sustainability Congress",
    startDate: new Date("2025-07-10"),
    endDate: new Date("2025-07-13"),
    place: "Berlim, Alemanha",
    submissionDeadline: new Date("2025-05-01"),
    reviewsPerArticle: 4,
  },
  {
    id: 4,
    name: "Data Science and Machine Learning Symposium",
    startDate: new Date("2025-08-18"),
    endDate: new Date("2025-08-21"),
    place: "Nova York, EUA",
    submissionDeadline: new Date("2025-06-05"),
    reviewsPerArticle: 3,
  },
  {
    id: 5,
    name: "Healthcare Technology Innovation Forum",
    startDate: new Date("2025-09-14"),
    endDate: new Date("2025-09-17"),
    place: "Toronto, Canadá",
    submissionDeadline: new Date("2025-07-01"),
    reviewsPerArticle: 2,
  },
  {
    id: 6,
    name: "Climate Change & Sustainability Congress",
    startDate: new Date("2025-07-10"),
    endDate: new Date("2025-07-13"),
    place: "Berlim, Alemanha",
    submissionDeadline: new Date("2025-05-01"),
    reviewsPerArticle: 4,
  },
  {
    id: 7,
    name: "Data Science and Machine Learning Symposium",
    startDate: new Date("2025-08-18"),
    endDate: new Date("2025-08-21"),
    place: "Nova York, EUA",
    submissionDeadline: new Date("2025-06-05"),
    reviewsPerArticle: 3,
  },
  {
    id: 8,
    name: "Healthcare Technology Innovation Forum",
    startDate: new Date("2025-09-14"),
    endDate: new Date("2025-09-17"),
    place: "Toronto, Canadá",
    submissionDeadline: new Date("2025-07-01"),
    reviewsPerArticle: 2,
  },
  {
    id: 9,
    name: "Climate Change & Sustainability Congress",
    startDate: new Date("2025-07-10"),
    endDate: new Date("2025-07-13"),
    place: "Berlim, Alemanha",
    submissionDeadline: new Date("2025-05-01"),
    reviewsPerArticle: 4,
  },
  {
    id: 10,
    name: "Data Science and Machine Learning Symposium",
    startDate: new Date("2025-08-18"),
    endDate: new Date("2025-08-21"),
    place: "Nova York, EUA",
    submissionDeadline: new Date("2025-06-05"),
    reviewsPerArticle: 3,
  },
  {
    id: 11,
    name: "Healthcare Technology Innovation Forum",
    startDate: new Date("2025-09-14"),
    endDate: new Date("2025-09-17"),
    place: "Toronto, Canadá",
    submissionDeadline: new Date("2025-07-01"),
    reviewsPerArticle: 2,
  },
];
