import { ICongress } from "@/types/congress";

export const fakeCongresses: ICongress[] = [
  {
    id: 1,
    name: "International Conference on Artificial Intelligence",
    startDate: new Date("2025-05-12"),
    imageThumbnail:
      "https://ifscc.org/wp-content/uploads/2024/10/096A1617-e1730297538579.jpg",
    endDate: new Date("2025-05-15"),
    modality: "PRESENTIAL", // "PRESENTIAL", "REMOTE", "SEMI-PRESENTIAL"
    descriptionTitle:
      "Venha participar da confêrencia internacional de inteligência artificial!",
    description: "A conferência irá contar com...",
    place: "São Paulo, Brasil",
    reviewDeadline: new Date("2025-03-14"),
    submissionDeadline: new Date("2025-03-20"),
    minReviewsPerArticle: 3,
    maxReviewsPerArticle: 5,
  },

  {
    id: 4,
    name: "Data Science and Machine Learning Symposium",
    startDate: new Date("2025-08-18"),
    endDate: new Date("2025-08-21"),
    place: "Nova York, EUA",
    modality: "REMOTE",
    descriptionTitle: "Avanços em Data Science e Machine Learning",
    description:
      "O simpósio trará especialistas de todo o mundo para apresentar pesquisas inovadoras em aprendizado de máquina, big data, IA ética e aplicações reais em diversos setores.",
    submissionDeadline: new Date("2025-06-05"),
    reviewDeadline: new Date("2025-05-05"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 3,
  },
  {
    id: 5,
    name: "Healthcare Technology Innovation Forum",
    startDate: new Date("2025-09-14"),
    endDate: new Date("2025-09-17"),
    place: "Toronto, Canadá",
    modality: "SEMI-PRESENTIAL",
    descriptionTitle: "Inovações tecnológicas para a saúde do futuro",
    description:
      "O fórum destacará novas tecnologias em telemedicina, dispositivos vestíveis, IA aplicada à saúde e soluções para melhorar o bem-estar global.",
    submissionDeadline: new Date("2025-07-01"),
    reviewDeadline: new Date("2025-06-01"),
    minReviewsPerArticle: 1,
    maxReviewsPerArticle: 2,
  },

  {
    id: 2,
    name: "Global Blockchain & Web3 Summit",
    startDate: new Date("2025-06-02"),
    endDate: new Date("2025-06-05"),
    place: "Lisboa, Portugal",
    modality: "SEMI-PRESENTIAL",
    descriptionTitle: "Descubra o futuro do Blockchain e da Web3",
    description:
      "O Global Blockchain & Web3 Summit reunirá líderes e inovadores para discutir soluções descentralizadas, NFTs, DAOs e a economia digital emergente.",
    submissionDeadline: new Date("2025-04-10"),
    reviewDeadline: new Date("2025-03-10"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 2,
  },
  {
    id: 3,
    name: "Climate Change & Sustainability Congress",
    startDate: new Date("2025-07-10"),
    endDate: new Date("2025-07-13"),
    place: "Berlim, Alemanha",
    modality: "PRESENTIAL",
    descriptionTitle: "Soluções globais para um planeta sustentável",
    description:
      "Este congresso internacional promove debates sobre mudanças climáticas, sustentabilidade urbana, energias renováveis e estratégias globais para reduzir emissões de carbono.",
    submissionDeadline: new Date("2025-05-01"),
    reviewDeadline: new Date("2025-04-01"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 4,
  },
  {
    id: 10,
    name: "Healthcare Technology Innovation Forum",
    startDate: new Date("2025-09-14"),
    endDate: new Date("2025-09-17"),
    place: "Toronto, Canadá",
    modality: "SEMI-PRESENTIAL",
    descriptionTitle: "Inovações tecnológicas para a saúde do futuro",
    description:
      "O fórum destacará novas tecnologias em telemedicina, dispositivos vestíveis, IA aplicada à saúde e soluções para melhorar o bem-estar global.",
    submissionDeadline: new Date("2025-07-01"),
    reviewDeadline: new Date("2025-06-01"),
    minReviewsPerArticle: 1,
    maxReviewsPerArticle: 2,
  },
  {
    id: 11,
    name: "International Conference on Artificial Intelligence",
    startDate: new Date("2025-05-12"),
    endDate: new Date("2025-05-15"),
    imageThumbnail:
      "https://ifscc.org/wp-content/uploads/2024/10/096A1617-e1730297538579.jpg",
    modality: "PRESENTIAL", // "PRESENTIAL", "REMOTE", "SEMI-PRESENTIAL"
    descriptionTitle:
      "Venha participar da conferencia internaciona de inteligência artificial!",
    description: "A conferência irá contar com...",
    place: "São Paulo, Brasil",
    reviewDeadline: new Date("2025-03-14"),
    submissionDeadline: new Date("2025-03-20"),
    minReviewsPerArticle: 3,
    maxReviewsPerArticle: 5,
  },
  {
    id: 12,
    name: "Global Blockchain & Web3 Summit",
    startDate: new Date("2025-06-02"),
    endDate: new Date("2025-06-05"),
    place: "Lisboa, Portugal",
    modality: "SEMI-PRESENTIAL",
    descriptionTitle: "Descubra o futuro do Blockchain e da Web3",
    description:
      "O Global Blockchain & Web3 Summit reunirá líderes e inovadores para discutir soluções descentralizadas, NFTs, DAOs e a economia digital emergente.",
    submissionDeadline: new Date("2025-04-10"),
    reviewDeadline: new Date("2025-03-10"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 2,
  },
  {
    id: 13,
    name: "Climate Change & Sustainability Congress",
    startDate: new Date("2025-07-10"),
    endDate: new Date("2025-07-13"),
    place: "Berlim, Alemanha",
    modality: "PRESENTIAL",
    descriptionTitle: "Soluções globais para um planeta sustentável",
    description:
      "Este congresso internacional promove debates sobre mudanças climáticas, sustentabilidade urbana, energias renováveis e estratégias globais para reduzir emissões de carbono.",
    submissionDeadline: new Date("2025-05-01"),
    reviewDeadline: new Date("2025-04-01"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 4,
  },
  {
    id: 14,
    name: "Data Science and Machine Learning Symposium",
    startDate: new Date("2025-08-18"),
    endDate: new Date("2025-08-21"),
    imageThumbnail:
      "https://ifscc.org/wp-content/uploads/2024/10/096A1617-e1730297538579.jpg",
    place: "Nova York, EUA",
    modality: "REMOTE",
    descriptionTitle: "Avanços em Data Science e Machine Learning",
    description:
      "O simpósio trará especialistas de todo o mundo para apresentar pesquisas inovadoras em aprendizado de máquina, big data, IA ética e aplicações reais em diversos setores.",
    submissionDeadline: new Date("2025-06-05"),
    reviewDeadline: new Date("2025-05-05"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 3,
  },
  {
    id: 6,
    name: "International Conference on Artificial Intelligence",
    startDate: new Date("2025-05-12"),
    endDate: new Date("2025-05-15"),
    modality: "PRESENTIAL", // "PRESENTIAL", "REMOTE", "SEMI-PRESENTIAL"
    descriptionTitle:
      "Venha participar da conferencia internaciona de inteligência artificial!",
    description: "A conferência irá contar com...",
    place: "São Paulo, Brasil",
    reviewDeadline: new Date("2025-03-14"),
    submissionDeadline: new Date("2025-03-20"),
    minReviewsPerArticle: 3,
    maxReviewsPerArticle: 5,
  },
  {
    id: 7,
    name: "Global Blockchain & Web3 Summit",
    startDate: new Date("2025-06-02"),
    endDate: new Date("2025-06-05"),
    place: "Lisboa, Portugal",
    modality: "SEMI-PRESENTIAL",
    descriptionTitle: "Descubra o futuro do Blockchain e da Web3",
    description:
      "O Global Blockchain & Web3 Summit reunirá líderes e inovadores para discutir soluções descentralizadas, NFTs, DAOs e a economia digital emergente.",
    submissionDeadline: new Date("2025-04-10"),
    reviewDeadline: new Date("2025-03-10"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 2,
  },
  {
    id: 8,
    name: "Climate Change & Sustainability Congress",
    startDate: new Date("2025-07-10"),
    endDate: new Date("2025-07-13"),
    place: "Berlim, Alemanha",
    modality: "PRESENTIAL",
    descriptionTitle: "Soluções globais para um planeta sustentável",
    description:
      "Este congresso internacional promove debates sobre mudanças climáticas, sustentabilidade urbana, energias renováveis e estratégias globais para reduzir emissões de carbono.",
    submissionDeadline: new Date("2025-05-01"),
    reviewDeadline: new Date("2025-04-01"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 4,
  },
  {
    id: 9,
    name: "Data Science and Machine Learning Symposium",
    startDate: new Date("2025-08-18"),
    endDate: new Date("2025-08-21"),
    imageThumbnail:
      "https://ifscc.org/wp-content/uploads/2024/10/096A1617-e1730297538579.jpg",
    place: "Nova York, EUA",
    modality: "REMOTE",
    descriptionTitle: "Avanços em Data Science e Machine Learning",
    description:
      "O simpósio trará especialistas de todo o mundo para apresentar pesquisas inovadoras em aprendizado de máquina, big data, IA ética e aplicações reais em diversos setores.",
    submissionDeadline: new Date("2025-06-05"),
    reviewDeadline: new Date("2025-05-05"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 3,
  },

  {
    id: 20,
    name: "Healthcare Technology Innovation Forum",
    startDate: new Date("2025-09-14"),
    endDate: new Date("2025-09-17"),
    place: "Toronto, Canadá",
    modality: "SEMI-PRESENTIAL",
    descriptionTitle: "Inovações tecnológicas para a saúde do futuro",
    description:
      "O fórum destacará novas tecnologias em telemedicina, dispositivos vestíveis, IA aplicada à saúde e soluções para melhorar o bem-estar global.",
    submissionDeadline: new Date("2025-07-01"),
    reviewDeadline: new Date("2025-06-01"),
    minReviewsPerArticle: 1,
    maxReviewsPerArticle: 2,
  },
  {
    id: 21,
    name: "International Conference on Artificial Intelligence",
    startDate: new Date("2025-05-12"),
    imageThumbnail:
      "https://ifscc.org/wp-content/uploads/2024/10/096A1617-e1730297538579.jpg",
    endDate: new Date("2025-05-15"),
    modality: "PRESENTIAL", // "PRESENTIAL", "REMOTE", "SEMI-PRESENTIAL"
    descriptionTitle:
      "Venha participar da conferencia internacional de inteligência artificial!",
    description: "A conferência irá contar com...",
    place: "São Paulo, Brasil",
    reviewDeadline: new Date("2025-03-14"),
    submissionDeadline: new Date("2025-03-20"),
    minReviewsPerArticle: 3,
    maxReviewsPerArticle: 5,
  },
  {
    id: 22,
    name: "Global Blockchain & Web3 Summit",
    startDate: new Date("2025-06-02"),
    endDate: new Date("2025-06-05"),
    place: "Lisboa, Portugal",
    modality: "SEMI-PRESENTIAL",
    descriptionTitle: "Descubra o futuro do Blockchain e da Web3",
    description:
      "O Global Blockchain & Web3 Summit reunirá líderes e inovadores para discutir soluções descentralizadas, NFTs, DAOs e a economia digital emergente.",
    submissionDeadline: new Date("2025-04-10"),
    reviewDeadline: new Date("2025-03-10"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 2,
  },
  {
    id: 23,
    name: "Climate Change & Sustainability Congress",
    startDate: new Date("2025-07-10"),
    endDate: new Date("2025-07-13"),
    place: "Berlim, Alemanha",
    modality: "PRESENTIAL",
    descriptionTitle: "Soluções globais para um planeta sustentável",
    description:
      "Este congresso internacional promove debates sobre mudanças climáticas, sustentabilidade urbana, energias renováveis e estratégias globais para reduzir emissões de carbono.",
    submissionDeadline: new Date("2025-05-01"),
    reviewDeadline: new Date("2025-04-01"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 4,
  },
  {
    id: 15,
    name: "Healthcare Technology Innovation Forum",
    startDate: new Date("2025-09-14"),
    endDate: new Date("2025-09-17"),
    place: "Toronto, Canadá",
    modality: "SEMI-PRESENTIAL",
    descriptionTitle: "Inovações tecnológicas para a saúde do futuro",
    description:
      "O fórum destacará novas tecnologias em telemedicina, dispositivos vestíveis, IA aplicada à saúde e soluções para melhorar o bem-estar global.",
    submissionDeadline: new Date("2025-07-01"),
    reviewDeadline: new Date("2025-06-01"),
    minReviewsPerArticle: 1,
    maxReviewsPerArticle: 2,
  },
  {
    id: 16,
    name: "International Conference on Artificial Intelligence",
    startDate: new Date("2025-05-12"),
    endDate: new Date("2025-05-15"),
    modality: "PRESENTIAL", // "PRESENTIAL", "REMOTE", "SEMI-PRESENTIAL"
    descriptionTitle:
      "Venha participar da conferencia internaciona de inteligência artificial!",
    description: "A conferência irá contar com...",
    place: "São Paulo, Brasil",
    reviewDeadline: new Date("2025-03-14"),
    submissionDeadline: new Date("2025-03-20"),
    minReviewsPerArticle: 3,
    maxReviewsPerArticle: 5,
  },
  {
    id: 17,
    name: "Global Blockchain & Web3 Summit",
    startDate: new Date("2025-06-02"),
    endDate: new Date("2025-06-05"),
    place: "Lisboa, Portugal",
    modality: "SEMI-PRESENTIAL",
    descriptionTitle: "Descubra o futuro do Blockchain e da Web3",
    description:
      "O Global Blockchain & Web3 Summit reunirá líderes e inovadores para discutir soluções descentralizadas, NFTs, DAOs e a economia digital emergente.",
    submissionDeadline: new Date("2025-04-10"),
    reviewDeadline: new Date("2025-03-10"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 2,
  },
  {
    id: 18,
    name: "Climate Change & Sustainability Congress",
    startDate: new Date("2025-07-10"),
    endDate: new Date("2025-07-13"),
    place: "Berlim, Alemanha",
    modality: "PRESENTIAL",
    descriptionTitle: "Soluções globais para um planeta sustentável",
    description:
      "Este congresso internacional promove debates sobre mudanças climáticas, sustentabilidade urbana, energias renováveis e estratégias globais para reduzir emissões de carbono.",
    submissionDeadline: new Date("2025-05-01"),
    reviewDeadline: new Date("2025-04-01"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 4,
  },
  {
    id: 19,
    name: "Data Science and Machine Learning Symposium",
    startDate: new Date("2025-08-18"),
    endDate: new Date("2025-08-21"),
    place: "Nova York, EUA",
    modality: "REMOTE",
    descriptionTitle: "Avanços em Data Science e Machine Learning",
    description:
      "O simpósio trará especialistas de todo o mundo para apresentar pesquisas inovadoras em aprendizado de máquina, big data, IA ética e aplicações reais em diversos setores.",
    submissionDeadline: new Date("2025-06-05"),
    reviewDeadline: new Date("2025-05-05"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 3,
  },
  {
    id: 24,
    name: "Data Science and Machine Learning Symposium",
    startDate: new Date("2025-08-18"),
    endDate: new Date("2025-08-21"),
    place: "Nova York, EUA",
    modality: "REMOTE",
    descriptionTitle: "Avanços em Data Science e Machine Learning",
    description:
      "O simpósio trará especialistas de todo o mundo para apresentar pesquisas inovadoras em aprendizado de máquina, big data, IA ética e aplicações reais em diversos setores.",
    submissionDeadline: new Date("2025-06-05"),
    reviewDeadline: new Date("2025-05-05"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 3,
  },

  {
    id: 30,
    name: "Healthcare Technology Innovation Forum",
    startDate: new Date("2025-09-14"),
    endDate: new Date("2025-09-17"),
    place: "Toronto, Canadá",
    modality: "SEMI-PRESENTIAL",
    descriptionTitle: "Inovações tecnológicas para a saúde do futuro",
    description:
      "O fórum destacará novas tecnologias em telemedicina, dispositivos vestíveis, IA aplicada à saúde e soluções para melhorar o bem-estar global.",
    submissionDeadline: new Date("2025-07-01"),
    reviewDeadline: new Date("2025-06-01"),
    minReviewsPerArticle: 1,
    maxReviewsPerArticle: 2,
  },
  {
    id: 31,
    name: "International Conference on Artificial Intelligence",
    startDate: new Date("2025-05-12"),
    endDate: new Date("2025-05-15"),
    modality: "PRESENTIAL", // "PRESENTIAL", "REMOTE", "SEMI-PRESENTIAL"
    descriptionTitle:
      "Venha participar da conferencia internaciona de inteligência artificial!",
    description: "A conferência irá contar com...",
    place: "São Paulo, Brasil",
    reviewDeadline: new Date("2025-03-14"),
    submissionDeadline: new Date("2025-03-20"),
    minReviewsPerArticle: 3,
    maxReviewsPerArticle: 5,
  },
  {
    id: 32,
    name: "Global Blockchain & Web3 Summit",
    startDate: new Date("2025-06-02"),
    endDate: new Date("2025-06-05"),
    place: "Lisboa, Portugal",
    modality: "SEMI-PRESENTIAL",
    descriptionTitle: "Descubra o futuro do Blockchain e da Web3",
    description:
      "O Global Blockchain & Web3 Summit reunirá líderes e inovadores para discutir soluções descentralizadas, NFTs, DAOs e a economia digital emergente.",
    submissionDeadline: new Date("2025-04-10"),
    reviewDeadline: new Date("2025-03-10"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 2,
  },
  {
    id: 33,
    name: "Climate Change & Sustainability Congress",
    startDate: new Date("2025-07-10"),
    endDate: new Date("2025-07-13"),
    place: "Berlim, Alemanha",
    modality: "PRESENTIAL",
    descriptionTitle: "Soluções globais para um planeta sustentável",
    description:
      "Este congresso internacional promove debates sobre mudanças climáticas, sustentabilidade urbana, energias renováveis e estratégias globais para reduzir emissões de carbono.",
    submissionDeadline: new Date("2025-05-01"),
    reviewDeadline: new Date("2025-04-01"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 4,
  },
  {
    id: 34,
    name: "Data Science and Machine Learning Symposium",
    startDate: new Date("2025-08-18"),
    endDate: new Date("2025-08-21"),
    place: "Nova York, EUA",
    modality: "REMOTE",
    descriptionTitle: "Avanços em Data Science e Machine Learning",
    description:
      "O simpósio trará especialistas de todo o mundo para apresentar pesquisas inovadoras em aprendizado de máquina, big data, IA ética e aplicações reais em diversos setores.",
    submissionDeadline: new Date("2025-06-05"),
    reviewDeadline: new Date("2025-05-05"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 3,
  },
  {
    id: 25,
    name: "Healthcare Technology Innovation Forum",
    startDate: new Date("2025-09-14"),
    endDate: new Date("2025-09-17"),
    place: "Toronto, Canadá",
    modality: "SEMI-PRESENTIAL",
    descriptionTitle: "Inovações tecnológicas para a saúde do futuro",
    description:
      "O fórum destacará novas tecnologias em telemedicina, dispositivos vestíveis, IA aplicada à saúde e soluções para melhorar o bem-estar global.",
    submissionDeadline: new Date("2025-07-01"),
    reviewDeadline: new Date("2025-06-01"),
    minReviewsPerArticle: 1,
    maxReviewsPerArticle: 2,
  },
  {
    id: 26,
    name: "International Conference on Artificial Intelligence",
    startDate: new Date("2025-05-12"),
    endDate: new Date("2025-05-15"),
    modality: "PRESENTIAL", // "PRESENTIAL", "REMOTE", "SEMI-PRESENTIAL"
    descriptionTitle:
      "Venha participar da conferencia internaciona de inteligência artificial!",
    description: "A conferência irá contar com...",
    place: "São Paulo, Brasil",
    reviewDeadline: new Date("2025-03-14"),
    submissionDeadline: new Date("2025-03-20"),
    minReviewsPerArticle: 3,
    maxReviewsPerArticle: 5,
  },
  {
    id: 27,
    name: "Global Blockchain & Web3 Summit",
    startDate: new Date("2025-06-02"),
    endDate: new Date("2025-06-05"),
    place: "Lisboa, Portugal",
    modality: "SEMI-PRESENTIAL",
    descriptionTitle: "Descubra o futuro do Blockchain e da Web3",
    description:
      "O Global Blockchain & Web3 Summit reunirá líderes e inovadores para discutir soluções descentralizadas, NFTs, DAOs e a economia digital emergente.",
    submissionDeadline: new Date("2025-04-10"),
    reviewDeadline: new Date("2025-03-10"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 2,
  },
  {
    id: 28,
    name: "Climate Change & Sustainability Congress",
    startDate: new Date("2025-07-10"),
    endDate: new Date("2025-07-13"),
    place: "Berlim, Alemanha",
    modality: "PRESENTIAL",
    descriptionTitle: "Soluções globais para um planeta sustentável",
    description:
      "Este congresso internacional promove debates sobre mudanças climáticas, sustentabilidade urbana, energias renováveis e estratégias globais para reduzir emissões de carbono.",
    submissionDeadline: new Date("2025-05-01"),
    reviewDeadline: new Date("2025-04-01"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 4,
  },
  {
    id: 29,
    name: "Data Science and Machine Learning Symposium",
    startDate: new Date("2025-08-18"),
    endDate: new Date("2025-08-21"),
    place: "Nova York, EUA",
    modality: "REMOTE",
    descriptionTitle: "Avanços em Data Science e Machine Learning",
    description:
      "O simpósio trará especialistas de todo o mundo para apresentar pesquisas inovadoras em aprendizado de máquina, big data, IA ética e aplicações reais em diversos setores.",
    submissionDeadline: new Date("2025-06-05"),
    reviewDeadline: new Date("2025-05-05"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 3,
  },
  {
    id: 35,
    name: "Healthcare Technology Innovation Forum",
    startDate: new Date("2025-09-14"),
    endDate: new Date("2025-09-17"),
    place: "Toronto, Canadá",
    modality: "SEMI-PRESENTIAL",
    descriptionTitle: "Inovações tecnológicas para a saúde do futuro",
    description:
      "O fórum destacará novas tecnologias em telemedicina, dispositivos vestíveis, IA aplicada à saúde e soluções para melhorar o bem-estar global.",
    submissionDeadline: new Date("2025-07-01"),
    reviewDeadline: new Date("2025-06-01"),
    minReviewsPerArticle: 1,
    maxReviewsPerArticle: 2,
  },
  {
    id: 36,
    name: "International Conference on Artificial Intelligence",
    startDate: new Date("2025-05-12"),
    endDate: new Date("2025-05-15"),
    modality: "PRESENTIAL", // "PRESENTIAL", "REMOTE", "SEMI-PRESENTIAL"
    descriptionTitle:
      "Venha participar da conferencia internaciona de inteligência artificial!",
    description: "A conferência irá contar com...",
    place: "São Paulo, Brasil",
    reviewDeadline: new Date("2025-03-14"),
    submissionDeadline: new Date("2025-03-20"),
    minReviewsPerArticle: 3,
    maxReviewsPerArticle: 5,
  },
  {
    id: 37,
    name: "Global Blockchain & Web3 Summit",
    startDate: new Date("2025-06-02"),
    endDate: new Date("2025-06-05"),
    place: "Lisboa, Portugal",
    modality: "SEMI-PRESENTIAL",
    descriptionTitle: "Descubra o futuro do Blockchain e da Web3",
    description:
      "O Global Blockchain & Web3 Summit reunirá líderes e inovadores para discutir soluções descentralizadas, NFTs, DAOs e a economia digital emergente.",
    submissionDeadline: new Date("2025-04-10"),
    reviewDeadline: new Date("2025-03-10"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 2,
  },
  {
    id: 38,
    name: "Climate Change & Sustainability Congress",
    startDate: new Date("2025-07-10"),
    endDate: new Date("2025-07-13"),
    place: "Berlim, Alemanha",
    modality: "PRESENTIAL",
    descriptionTitle: "Soluções globais para um planeta sustentável",
    description:
      "Este congresso internacional promove debates sobre mudanças climáticas, sustentabilidade urbana, energias renováveis e estratégias globais para reduzir emissões de carbono.",
    submissionDeadline: new Date("2025-05-01"),
    reviewDeadline: new Date("2025-04-01"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 4,
  },
  {
    id: 39,
    name: "Data Science and Machine Learning Symposium",
    startDate: new Date("2025-08-18"),
    endDate: new Date("2025-08-21"),
    place: "Nova York, EUA",
    modality: "REMOTE",
    descriptionTitle: "Avanços em Data Science e Machine Learning",
    description:
      "O simpósio trará especialistas de todo o mundo para apresentar pesquisas inovadoras em aprendizado de máquina, big data, IA ética e aplicações reais em diversos setores.",
    submissionDeadline: new Date("2025-06-05"),
    reviewDeadline: new Date("2025-05-05"),
    minReviewsPerArticle: 2,
    maxReviewsPerArticle: 3,
  },
  {
    id: 40,
    name: "Healthcare Technology Innovation Forum",
    startDate: new Date("2025-09-14"),
    endDate: new Date("2025-09-17"),
    place: "Toronto, Canadá",
    modality: "SEMI-PRESENTIAL",
    descriptionTitle: "Inovações tecnológicas para a saúde do futuro",
    description:
      "O fórum destacará novas tecnologias em telemedicina, dispositivos vestíveis, IA aplicada à saúde e soluções para melhorar o bem-estar global.",
    submissionDeadline: new Date("2025-07-01"),
    reviewDeadline: new Date("2025-06-01"),
    minReviewsPerArticle: 1,
    maxReviewsPerArticle: 2,
  },
];
