import { IArticle, IArticleRanking } from "@/types/articles";

export const FakeArticles: IArticle[] = [
  {
    id: 1,
    description: "Análise sobre os impactos da IA na educação moderna",
    body: "ZGVtb19jb250ZW50X2FydGljbGU=",
    title: "Inteligência Artificial na Educação",
    knowledgeAreas: ["Educação", "Tecnologia"],
    format: "PDF",
    publishedAt: new Date("2025-01-10"),
    congressId: 3,
    articlesUsers: [5, 12],
    review: [3, 7],
  },
  {
    id: 2,
    description: "Explorando tendências em energias renováveis",
    body: "ZGVtb19jb250ZW50X2FydGljbGU=",
    title: "O Futuro da Energia Solar",
    knowledgeAreas: ["Engenharia", "Sustentabilidade"],
    format: "HTML",
    publishedAt: new Date("2025-01-12"),
    congressId: 6,
    articlesUsers: [9, 21],
    review: [2],
  },
  {
    id: 3,
    description: "Discussão sobre sistemas distribuídos",
    body: "ZGVtb19jb250ZW50X2FydGljbGU=",
    title: "Arquiteturas Escaláveis na Nuvem",
    knowledgeAreas: ["Computação", "Sistemas Distribuídos"],
    format: "MARKDOWN",
    publishedAt: new Date("2025-02-01"),
    congressId: 9,
    articlesUsers: [14],
    review: [8, 11],
  },
  {
    id: 4,
    description: "Uso de blockchain em registros médicos",
    body: "ZGVtb19jb250ZW50X2FydGljbGU=",
    title: "Blockchain na Saúde",
    knowledgeAreas: ["Saúde", "Blockchain"],
    format: "PDF",
    publishedAt: new Date("2025-02-14"),
    congressId: 3,
    articlesUsers: [7, 19],
    review: [],
  },
  {
    id: 5,
    description: "Abordagem crítica sobre redes sociais",
    body: "ZGVtb19jb250ZW50X2FydGljbGU=",
    title: "Redes Sociais e Sociedade",
    knowledgeAreas: ["Comunicação", "Psicologia"],
    format: "HTML",
    publishedAt: new Date("2025-03-01"),
    congressId: 6,
    articlesUsers: [11, 29],
    review: [4],
  },
  {
    id: 6,
    description: "Avanços em veículos autônomos",
    body: "ZGVtb19jb250ZW50X2FydGljbGU=",
    title: "Carros Autônomos: Desafios e Oportunidades",
    knowledgeAreas: ["Engenharia", "IA"],
    format: "PDF",
    publishedAt: new Date("2025-03-15"),
    congressId: 9,
    articlesUsers: [17],
    review: [6, 10],
  },
  {
    id: 7,
    description: "Efeitos do aquecimento global nas cidades costeiras",
    body: "ZGVtb19jb250ZW50X2FydGljbGU=",
    title: "Mudanças Climáticas e Impactos Urbanos",
    knowledgeAreas: ["Meio Ambiente", "Geografia"],
    format: "MARKDOWN",
    publishedAt: new Date("2025-03-20"),
    congressId: 3,
    articlesUsers: [8, 23],
    review: [9],
  },
  {
    id: 8,
    description: "Estudo sobre big data em governos",
    body: "ZGVtb19jb250ZW50X2FydGljbGU=",
    title: "Big Data e Políticas Públicas",
    knowledgeAreas: ["Computação", "Gestão Pública"],
    format: "HTML",
    publishedAt: new Date("2025-04-02"),
    congressId: 6,
    articlesUsers: [10],
    review: [13, 15],
  },
  {
    id: 9,
    description: "Exploração do design sustentável",
    body: "ZGVtb19jb250ZW50X2FydGljbGU=",
    title: "Arquitetura Verde",
    knowledgeAreas: ["Design", "Sustentabilidade"],
    format: "PDF",
    publishedAt: new Date("2025-04-18"),
    congressId: 9,
    articlesUsers: [2, 6],
    review: [],
  },
  {
    id: 10,
    description: "A evolução dos dispositivos móveis",
    body: "ZGVtb19jb250ZW50X2FydGljbGU=",
    title: "Do PDA ao Smartphone",
    knowledgeAreas: ["Tecnologia", "História"],
    format: "MARKDOWN",
    publishedAt: new Date("2025-05-01"),
    congressId: 3,
    articlesUsers: [1, 30],
    review: [12],
  },
  {
    id: 11,
    description: "Aplicações da biotecnologia na agricultura",
    body: "ZGVtb19jb250ZW50X2FydGljbGU=",
    title: "Agricultura 4.0",
    knowledgeAreas: ["Agronomia", "Biotecnologia"],
    format: "PDF",
    publishedAt: new Date("2025-05-10"),
    congressId: 6,
    articlesUsers: [15, 26],
    review: [5],
  },
  {
    id: 12,
    description: "Segurança cibernética e ataques recentes",
    body: "ZGVtb19jb250ZW50X2FydGljbGU=",
    title: "Cibersegurança em 2025",
    knowledgeAreas: ["Segurança", "Computação"],
    format: "HTML",
    publishedAt: new Date("2025-05-20"),
    congressId: 9,
    articlesUsers: [12, 24],
    review: [],
  },
  {
    id: 13,
    description: "Uso de realidade aumentada em medicina",
    body: "ZGVtb19jb250ZW50X2FydGljbGU=",
    title: "Realidade Aumentada na Cirurgia",
    knowledgeAreas: ["Saúde", "Tecnologia"],
    format: "PDF",
    publishedAt: new Date("2025-06-02"),
    congressId: 3,
    articlesUsers: [18, 28],
    review: [16],
  },
  {
    id: 14,
    description: "Estudo sobre impacto da música no humor",
    body: "ZGVtb19jb250ZW50X2FydGljbGU=",
    title: "Psicologia da Música",
    knowledgeAreas: ["Psicologia", "Artes"],
    format: "MARKDOWN",
    publishedAt: new Date("2025-06-15"),
    congressId: 6,
    articlesUsers: [4, 32],
    review: [20],
  },
  {
    id: 15,
    description: "Reflexões sobre ética em inteligência artificial",
    body: "ZGVtb19jb250ZW50X2FydGljbGU=",
    title: "Ética na IA",
    knowledgeAreas: ["Filosofia", "Tecnologia"],
    format: "PDF",
    publishedAt: new Date("2025-06-28"),
    congressId: 9,
    articlesUsers: [3, 22],
    review: [14, 19],
  },
];

export const FakeArticleRankings: IArticleRanking[] = [
  {
    id: 1,
    url: "https://example.com/article/1",
    title: "Inteligência Artificial na Educação",
    finalScore: 4.7,
    congressId: 3,
  },
  {
    id: 2,
    url: "https://example.com/article/2",
    title: "O Futuro da Energia Solar",
    finalScore: 3.2,
    congressId: 6,
  },
  {
    id: 3,
    url: "https://example.com/article/3",
    title: "Arquiteturas Escaláveis na Nuvem",
    finalScore: 5.0,
    congressId: 9,
  },
  {
    id: 4,
    url: "https://example.com/article/4",
    title: "Blockchain na Saúde",
    finalScore: 2.8,
    congressId: 3,
  },
  {
    id: 5,
    url: "https://example.com/article/5",
    title: "Redes Sociais e Sociedade",
    finalScore: 4.1,
    congressId: 6,
  },
  {
    id: 6,
    url: "https://example.com/article/6",
    title: "Carros Autônomos: Desafios e Oportunidades",
    finalScore: 0.9,
    congressId: 9,
  },
  {
    id: 7,
    url: "https://example.com/article/7",
    title: "Mudanças Climáticas e Impactos Urbanos",
    finalScore: 3.6,
    congressId: 3,
  },
  {
    id: 8,
    url: "https://example.com/article/8",
    title: "Big Data e Políticas Públicas",
    finalScore: 2.3,
    congressId: 6,
  },
  {
    id: 9,
    url: "https://example.com/article/9",
    title: "Arquitetura Verde",
    finalScore: 1.4,
    congressId: 9,
  },
  {
    id: 10,
    url: "https://example.com/article/10",
    title: "Do PDA ao Smartphone",
    finalScore: 4.9,
    congressId: 3,
  },
  {
    id: 11,
    url: "https://example.com/article/11",
    title: "Agricultura 4.0",
    finalScore: 3.0,
    congressId: 6,
  },
  {
    id: 12,
    url: "https://example.com/article/12",
    title: "Cibersegurança em 2025",
    finalScore: 2.5,
    congressId: 9,
  },
  {
    id: 13,
    url: "https://example.com/article/13",
    title: "Realidade Aumentada na Cirurgia",
    finalScore: 0.3,
    congressId: 3,
  },
  {
    id: 14,
    url: "https://example.com/article/14",
    title: "Psicologia da Música",
    finalScore: 4.4,
    congressId: 6,
  },
  {
    id: 15,
    url: "https://example.com/article/15",
    title: "Ética na IA",
    finalScore: 1.7,
    congressId: 9,
  },
];
